name: graphql_client
description: A general GraphQL client, bringing all the features from a modern GraphQL client to one easy to use package.
version: 1.0.0-beta.1+1
authors:
  - Eus Dima <eus@zinoapp.com>
  - Zino Hofmann <zino@zinoapp.com>
  - TruongSinh Tran-Nguyen <i@truongsinh.pro>
homepage: https://github.com/zino-app/graphql-flutter/tree/next

dependencies:
  meta: ^1.1.6
  http: ^0.12.0
  mime: ^0.9.6+2
  path: ^1.6.2
  http_parser: ^3.1.3
  uuid_enhanced: ^3.0.0
  graphql_parser: ^1.1.1

dev_dependencies:
  perfectionist: ^2.0.0
  mockito: ^4.0.0
  test: ^1.3.0

environment:
  sdk: ">=2.1.0 <3.0.0"
