name: graphql_common
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.6 <3.0.0'

dependencies:
  logger: ^1.1.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  graphql:
    path: ../graphql
