// initially auto-generated by test_coverage,
// but that project is unmaintained https://github.com/pulyaevskiy/test-coverage/issues/40

import 'anonymous_operations_test.dart' as anonymous_operations_test;
import 'cache/graphql_cache_test.dart' as cache_graphql_cache_test;
import 'cache/store_test.dart' as cache_store_test;
import 'fetch_policy_test.dart' as fetch_policy_test;
import 'graphql_client_test.dart' as graphql_client_test;
import 'query_options_test.dart' as query_options_test;
import 'websocket_test.dart' as websocket_test;

void main() {
  query_options_test.main();
  cache_store_test.main();
  cache_graphql_cache_test.main();
  fetch_policy_test.main();
  anonymous_operations_test.main();
  websocket_test.main();
  graphql_client_test.main();
}
